services:
  backend:
    image: kinosoft/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: kinosoft/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
